/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mri-department.glb --transform 
Files: mri-department.glb [2.17MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/buildings/mri-department-transformed.glb [32.99KB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function MRIDepartment(props) {
  const { nodes, materials } = useGLTF(
    "/models/buildings/mri-department-transformed.glb"
  );

  const { position, rotation } = useControls("MRI Department", {
    position: {
      value: {
        x: 20,
        y: 0,
        z: 80,
      },
      step: 0.01,
    },
    rotation: {
      value: -1.29,
      step: 0.01,
    },
  });

  return (
    <group
      {...props}
      dispose={null}
      position={[position.x, position.y, position.z]}
      rotation-y={rotation}
    >
      <mesh
        geometry={nodes.walls.geometry}
        material={materials.wallMaterial}
        position={[34.066, 0.053, -35.187]}
      />
      <instancedMesh
        args={[nodes.DoorFrane003.geometry, materials.doorMaterial, 7]}
        instanceMatrix={nodes.DoorFrane003.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door006.geometry, materials.doorMaterial, 7]}
        instanceMatrix={nodes.Door006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back006.geometry, materials.handleMaterial, 28]}
        instanceMatrix={nodes.Handle_Back006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door007.geometry, materials.doorMaterial, 7]}
        instanceMatrix={nodes.Door007.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane004.geometry, materials.doorMaterial, 9]}
        instanceMatrix={nodes.DoorFrane004.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door008.geometry, materials.doorMaterial, 9]}
        instanceMatrix={nodes.Door008.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back008.geometry, materials.handleMaterial, 18]}
        instanceMatrix={nodes.Handle_Back008.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/buildings/mri-department-transformed.glb");
