/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hoppy.glb --transform
Files: hoppy.glb [679.98KB] > /Users/cex/Desktop/projects/RxVR-R3F/public/models/AnimalGuides/hoppy-transformed.glb [286.82KB] (58%)
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useInteraction, useTeleportation } from "@react-three/xr";
import teleportObject from "../../util/teleportObject";
import FloatingButton from "./Buttons/FloatingButton";
import * as THREE from "three";
import { useControls } from "leva";
import { useFrame } from "@react-three/fiber";

export function Hoppy(props) {
  const hoppy = useGLTF("/models/hoppy/hoppy.glb");

  const { position } = useControls("Hoppy", {
    position: { value: { x: 0, y: 0, z: 0 }, step: 0.1 },
  });

  return (
    <>
      <primitive
        ref={hoppy}
        object={hoppy.scene}
        {...props}
        position={[position.x, position.y, position.z]}
      ></primitive>
    </>
  );
}

useGLTF.preload("/models/hoppy/hoppy-transformed.glb");
