/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 navmesh.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Navmesh(props) {
  const { nodes, materials } = useGLTF("/models/navmesh/navmesh.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.navmesh.geometry}
        material={nodes.navmesh.material}
        position={[-36.706, -0.004, 2.542]}
        scale={[1, 1, 0.706]}
      />
    </group>
  );
}

useGLTF.preload("/models/navmesh/navmesh.glb");
