/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Treadmill.glb --transform 
Files: Treadmill.glb [26.41KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\gym\Treadmill-transformed.glb [4.9KB] (81%)
*/

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";

// export function Treadmills({
//   position = [0, 0, 0],
//   scale = 100,
//   props,
//   rotation = [0, 0, 0],
// }) {
//   const { nodes, materials } = useGLTF("/models/gym/treadmill2.glb");
//   return (
//     <group
//       position={position}
//       {...props}
//       dispose={null}
//       scale={scale}
//       rotation={rotation}
//     >
//       <mesh
//         geometry={nodes.Treadmill.geometry}
//         material={materials.Treadmill}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/gym/treadmill2.glb");

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Treadmills({
  position = [0, 0, 0],
  scale = 0.1,
  props,
  rotation = [0, 0, 0],
}) {
  const { nodes, materials } = useGLTF(
    "/models/gym/treadmill2-transformed.glb"
  );
  return (
    <group
      position={position}
      {...props}
      dispose={null}
      scale={scale}
      rotation={rotation}
    >
      <mesh
        geometry={nodes.pCylinder2_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

useGLTF.preload("/models/gym/treadmill2-transformed.glb");
