/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c_arm_xray_device.glb --transform 
Files: c_arm_xray_device.glb [612.34KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\c_arm_xray_device-transformed.glb [45.38KB] (93%)
Author: laurentiubodisteanu (https://sketchfab.com/laurentiubodisteanu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-arm-xray-device-08e65d9a5caa4dcf9338e1b980a9ec00
Title: C Arm Xray Device
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function XRayMachine(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/c_arm_xray_device-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.LB_CArmXrayDevice_Lambert_MAT_01_0.geometry}
        material={materials.Lambert_MAT_01}
      />
    </group>
  );
}

useGLTF.preload("/models/xray/c_arm_xray_device-transformed.glb");
