/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 DeskCorner.glb --transform 
Files: DeskCorner.glb [29.04KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\DeskCorner-transformed.glb [3.06KB] (89%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function DeskCorner(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/DeskCorner-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.deskCorner.geometry} material={materials.wood} />
      <mesh geometry={nodes.drawer.geometry} material={materials.metal} />
    </group>
  );
}

useGLTF.preload("/models/xray/DeskCorner-transformed.glb");
