/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 GreenWChair.glb --transform 
Files: GreenWChair.glb [146.99KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\GreenWChair-transformed.glb [9.44KB] (94%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GreenChair(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/GreenWChair-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.group1245598860.geometry}
        material={materials.mat11}
      />
      <mesh
        geometry={nodes.group1994826846.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group646429156.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group2011453973.geometry}
        material={materials.mat23}
      />
    </group>
  );
}

useGLTF.preload("/models/xray/GreenWChair-transformed.glb");
