/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 HouseplantBlack.glb --transform 
Files: HouseplantBlack.glb [16.64KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\plants\HouseplantBlack-transformed.glb [5.86KB] (65%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PlantBlack(props) {
  const { nodes, materials } = useGLTF(
    "/models/plants/HouseplantBlack-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          geometry={nodes.Houseplant_7_1.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Houseplant_7_2.geometry}
          material={materials.Brown}
        />
        <mesh
          geometry={nodes.Houseplant_7_3.geometry}
          material={materials.Plant_Green}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/HouseplantBlack-transformed.glb");
