/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 MedicalCabinet.glb --transform 
Files: MedicalCabinet.glb [52.87KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\MedicalCabinet-transformed.glb [19.55KB] (63%)
Author: BillyJJackson (https://sketchfab.com/pistonstone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medicine-wall-cupboard-hospital-3251d73995f54398b118d1aa0bb34489
Title: Medicine Wall Cupboard, Hospital
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cabinet(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/MedicalCabinet-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["MedicineWallCupboard_medince-cupboard-wall_Baked_0"].geometry
        }
        material={materials["medince-cupboard-wall_Baked"]}
      />
    </group>
  );
}

useGLTF.preload("/models/xray/MedicalCabinet-transformed.glb");
