/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Mirror.glb --transform 
Files: Mirror.glb [4.07KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\Mirror-transformed.glb [2.09KB] (49%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mirror(props) {
  const { nodes, materials } = useGLTF("/models/xray/Mirror-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mirror.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/models/xray/Mirror-transformed.glb");
