/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SingleBin.glb --transform 
Files: SingleBin.glb [8.35KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\xray\SingleBin-transformed.glb [3.2KB] (62%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SingleBin(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/SingleBin-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh1303551656.geometry}
        material={materials.mat11}
      />
      <mesh
        geometry={nodes.mesh1303551656_1.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh1303551656_2.geometry}
        material={materials.mat23}
      />
    </group>
  );
}

useGLTF.preload("/models/xray/SingleBin-transformed.glb");
