/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [44.03KB] > /Users/cex/Desktop/projects/RxVR-R3F/public/models/x-ray_board/scene-transformed.glb [1.09MB] (-2383%)
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medical-x-ray-image-viewer-200-uploads-1caaa90f0e6b48d08109e517ddd8aab0
Title: Medical X-ray Image Viewer - 200 Uploads!
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function XRayBoard(props) {
  const { nodes, materials } = useGLTF(
    "/models/xray/xray-board-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.box001_low_box_0.geometry}
        material={materials.material}
      />
      <mesh
        geometry={nodes.x_1_low_XRAY_0.geometry}
        material={materials.XRAY}
      />
      <mesh
        geometry={nodes.glass_low_glass_0.geometry}
        material={materials.glass}
      />
    </group>
  );
}

useGLTF.preload("/models/xray/xray-board-transformed.glb");
