/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 xray-department.glb --transform 
Files: xray-department.glb [1.54MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/buildings/xray-department-transformed.glb [37.53KB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function XrayDepartment(props) {
  const { nodes, materials } = useGLTF(
    "/models/buildings/xray-department-transformed.glb"
  );

  const { position, rotation } = useControls("XRay Department", {
    position: {
      value: {
        x: 111.5,
        y: 0,
        z: -28.5,
      },
      step: 0.01,
    },
    rotation: {
      value: -1.29,
      step: 0.01,
    },
  });

  return (
    <group
      {...props}
      dispose={null}
      position={[position.x, position.y, position.z]}
      rotation-y={rotation}
    >
      <mesh
        geometry={nodes.walls.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.DoorFrame.geometry}
        material={materials.PaletteMaterial003}
        position={[17.729, 0.053, -1.008]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.WindowL.geometry}
        material={materials.PaletteMaterial004}
        position={[22.022, 1.378, -8.235]}
      />
      <mesh
        geometry={nodes.Handle.geometry}
        material={materials.PaletteMaterial002}
        position={[22.057, 1.853, -8.199]}
      />
      <instancedMesh
        args={[nodes.Handle_Back.geometry, materials.PaletteMaterial002, 16]}
        instanceMatrix={nodes.Handle_Back.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane004.geometry, materials.PaletteMaterial003, 9]}
        instanceMatrix={nodes.DoorFrane004.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door008.geometry, materials.PaletteMaterial003, 9]}
        instanceMatrix={nodes.Door008.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back008.geometry, materials.PaletteMaterial002, 18]}
        instanceMatrix={nodes.Handle_Back008.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/buildings/xray-department-transformed.glb");
