/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 deskwithchair.glb --transform 
Files: deskwithchair.glb [1.4MB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\desks-chairs\deskwithchair-transformed.glb [65.52KB] (95%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function DeskChair(props) {
  const { nodes, materials } = useGLTF(
    "/models/desks-chairs/deskwithchair-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Chair.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("/models/desks-chairs/deskwithchair-transformed.glb");
