/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hospital_exam_table.glb --transform 
Files: hospital_exam_table.glb [1.6MB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\desks-chairs\hospital_exam_table-transformed.glb [104.79KB] (93%)
Author: Robin.Sasi.Kumar (https://sketchfab.com/Robin.Sasi.Kumar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hospital-table-efadeb7f31284e31a33e1572abab4f96
Title: Hospital Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ExamTable(props) {
  const { nodes, materials } = useGLTF(
    "/models/desks-chairs/hospital_exam_table-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        position={[-2.424, 1.27, 0.027]}
        scale={[1, 0.05, 1]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.003"]}
        position={[-1.067, 0.104, 0.106]}
        scale={[1, 0.13, 0.233]}
      />
    </group>
  );
}

useGLTF.preload("/models/desks-chairs/hospital_exam_table-transformed.glb");
