/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hospital_table.glb --transform 
Files: hospital_table.glb [58.3KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\desks-chairs\hospital_table-transformed.glb [16.02KB] (73%)
Author: RigidStudios (https://sketchfab.com/RigidStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hospital-table-mc-model-c229ec7fe42440f1847ea69b13082328
Title: Hospital Table - MC Model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function DoctorTable(props) {
  const { nodes, materials } = useGLTF(
    "/models/desks-chairs/hospital_table-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.material_1}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material_2}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.material_3}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.material_4}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.material_5}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.material_6}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.material_7}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.material_8}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.material_9}
      />
    </group>
  );
}

useGLTF.preload("/models/desks-chairs/hospital_table-transformed.glb");
