/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WoodenChair.glb --transform 
Files: WoodenChair.glb [13.36KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\desks-chairs\WoodenChair-transformed.glb [2.36KB] (82%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WoodenChair(props) {
  const { nodes, materials } = useGLTF(
    "/models/desks-chairs/WoodenChair-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair_1.geometry} material={materials.Wood} />
    </group>
  );
}

useGLTF.preload("/models/desks-chairs/WoodenChair-transformed.glb");
