/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/reception/waiting-chairs/scene.gltf --transform 
Files: ./public/models/reception/waiting-chairs/scene.gltf [5.62KB] > /Users/cex/Desktop/projects/RxVR-2/scene-transformed.glb [164.9KB] (-2834%)
Author: creative_beast (https://sketchfab.com/creative_beast)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/waiting-chair-76c028f787e049e4b6c3b8550f015f23
Title: Waiting Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WaitingChairs(props) {
  const { nodes, materials } = useGLTF(
    "/models/reception/waiting-chairs/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Waiting_Bench_(3_Seats)_Waiting_Bench_0"].geometry}
        material={materials.Waiting_Bench}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/reception/waiting-chairs/scene-transformed.glb");
