/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lobby-and-main-concourse-2.glb --transform 
Files: lobby-and-main-concourse-2.glb [9.08MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/buildings/lobby-and-main-concourse-2-transformed.glb [86.27KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useControls } from "leva";

export function LobbyAndMainConcourse(props) {
  const { nodes, materials } = useGLTF(
    "/models/buildings/lobby-and-main-concourse-3-transformed.glb"
  );

  const temporaryGlassMaterial = new THREE.MeshBasicMaterial({
    color: "white",
  });

  const { position, rotation } = useControls("Lobby And Main Concourse", {
    position: {
      value: {
        x: 23.8,
        y: 0,
        z: 6.7,
      },
      step: 0.1,
    },
    rotation: {
      value: 0.28,
      step: 0.01,
    },
  });
  return (
    <group
      {...props}
      dispose={null}
      position={[position.x, position.y, position.z]}
      rotation-y={rotation}
    >
      <mesh
        geometry={nodes.WALLS.geometry}
        material={materials.PaletteMaterial001}
      />
      <instancedMesh
        args={[nodes.CTRL_Baseboard.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.CTRL_Baseboard.instanceMatrix}
      />
      {/* <instancedMesh
        args={[nodes.CTRL_Hole.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.CTRL_Hole.instanceMatrix}
      /> */}
      <instancedMesh
        args={[nodes.DoorFrane.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.DoorFrane.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.Door.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back.geometry, materials.PaletteMaterial001, 48]}
        instanceMatrix={nodes.Handle_Back.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door001.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.Door001.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.CTRL_Baseboard014.geometry,
          materials.PaletteMaterial001,
          19,
        ]}
        instanceMatrix={nodes.CTRL_Baseboard014.instanceMatrix}
      />
      {/* <instancedMesh
        args={[nodes.CTRL_Hole014.geometry, materials.PaletteMaterial001, 19]}
        instanceMatrix={nodes.CTRL_Hole014.instanceMatrix}
      /> */}
      <instancedMesh
        args={[nodes.DoorFrane014.geometry, nodes.DoorFrane014.material, 19]}
        instanceMatrix={nodes.DoorFrane014.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back028.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.Handle_Back028.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door029.geometry, materials.PaletteMaterial001, 18]}
        instanceMatrix={nodes.Door029.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle.geometry, materials.PaletteMaterial001, 44]}
        instanceMatrix={nodes.Handle.instanceMatrix}
      />
      {/* <instancedMesh
        args={[nodes.CTRL_Hole036.geometry, materials.PaletteMaterial001, 8]}
        instanceMatrix={nodes.CTRL_Hole036.instanceMatrix}
      /> */}
      <instancedMesh
        args={[nodes.WindowFrane002.geometry, nodes.WindowFrane002.material, 8]}
        instanceMatrix={nodes.WindowFrane002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Windows_Sill002.geometry, materials.PaletteMaterial001, 8]}
        instanceMatrix={nodes.Windows_Sill002.instanceMatrix}
      />
      {/* <instancedMesh
        args={[nodes.CTRL_Hole046.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.CTRL_Hole046.instanceMatrix}
      /> */}
      <instancedMesh
        args={[nodes.WindowFrane011.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.WindowFrane011.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Windows_Sill011.geometry,
          materials.PaletteMaterial001,
          12,
        ]}
        instanceMatrix={nodes.Windows_Sill011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL002.geometry, temporaryGlassMaterial, 8]}
        instanceMatrix={nodes.WindowL002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL002_1.geometry, temporaryGlassMaterial, 8]}
        instanceMatrix={nodes.WindowL002_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR002.geometry, temporaryGlassMaterial, 8]}
        instanceMatrix={nodes.WindowR002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR002_1.geometry, temporaryGlassMaterial, 8]}
        instanceMatrix={nodes.WindowR002_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL011.geometry, temporaryGlassMaterial, 12]}
        instanceMatrix={nodes.WindowL011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL011_1.geometry, temporaryGlassMaterial, 12]}
        instanceMatrix={nodes.WindowL011_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR011.geometry, temporaryGlassMaterial, 12]}
        instanceMatrix={nodes.WindowR011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR011_1.geometry, temporaryGlassMaterial, 12]}
        instanceMatrix={nodes.WindowR011_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/buildings/lobby-and-main-concourse-3-transformed.glb");
