/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lobby-and-main-concourse-4.glb --transform 
Files: lobby-and-main-concourse-4.glb [4.03MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/buildings/lobby-and-main-concourse-4-transformed.glb [50.25KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LobbyAndMainConcourse4(props) {
  const { nodes, materials } = useGLTF(
    "/models/buildings/lobby-and-main-concourse-4-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WALLS.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.WindowL.geometry}
        material={materials.PaletteMaterial002}
        position={[0.761, 0.025, -13.704]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <instancedMesh
        args={[nodes.DoorFrane014.geometry, nodes.DoorFrane014.material, 19]}
        instanceMatrix={nodes.DoorFrane014.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door028.geometry, materials.PaletteMaterial001, 19]}
        instanceMatrix={nodes.Door028.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back028.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.Handle_Back028.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane001.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.DoorFrane001.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door002.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.Door002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back002.geometry, materials.PaletteMaterial001, 48]}
        instanceMatrix={nodes.Handle_Back002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door003.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.Door003.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowFrane011.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.WindowFrane011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle022.geometry, materials.PaletteMaterial001, 24]}
        instanceMatrix={nodes.Handle022.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Windows_Sill011.geometry,
          materials.PaletteMaterial001,
          12,
        ]}
        instanceMatrix={nodes.Windows_Sill011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL011.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.WindowL011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL011_1.geometry, materials.PaletteMaterial002, 12]}
        instanceMatrix={nodes.WindowL011_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR011.geometry, materials.PaletteMaterial001, 12]}
        instanceMatrix={nodes.WindowR011.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR011_1.geometry, materials.PaletteMaterial002, 12]}
        instanceMatrix={nodes.WindowR011_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/buildings/lobby-and-main-concourse-4-transformed.glb");
