/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 roof.glb --transform 
Files: roof.glb [61.51KB] > /Users/cex/Desktop/projects/RxVR-2/public/models/roof/roof-transformed.glb [8.77KB] (86%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function Roof(props) {
  const { nodes, materials } = useGLTF("/models/roof/roof-transformed.glb");

  const { position, rotation } = useControls("Roof", {
    position: {
      value: {
        x: 55.6,
        y: 0,
        z: -14.8,
      },
      step: 0.1,
    },
    rotation: {
      value: 0.28,
      step: 0.01,
    },
  });

  return (
    <group
      {...props}
      dispose={null}
      position={[position.x, position.y, position.z]}
      rotation-y={rotation}
    >
      <mesh geometry={nodes.FLOOR002.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.FLOOR001.geometry}
        material={materials.ceilingMaterial}
        position={[0, -3.01, 0]}
      />
      <instancedMesh
        args={[nodes.Window023.geometry, materials.PVC, 17]}
        instanceMatrix={nodes.Window023.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Window023_1.geometry, materials.PVC, 17]}
        instanceMatrix={nodes.Window023_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Window023_2.geometry, materials.PVC, 17]}
        instanceMatrix={nodes.Window023_2.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Window023_3.geometry, materials.PVC, 17]}
        instanceMatrix={nodes.Window023_3.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/roof/roof-transformed.glb");
