/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 MRIControlPanel.glb --transform 
Files: MRIControlPanel.glb [173.49KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\mri\MRIControlPanel-transformed.glb [30.56KB] (82%)
Author: Jenson_A (https://sketchfab.com/Jenson_A)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/let-me-out-control-pannel-78d1d1863f3247ae92eb6b2e2934c7a4
Title: Let Me Out - Control Pannel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MRIControlPanel(props) {
  const { nodes, materials } = useGLTF(
    "/models/mri/MRIControlPanel-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Desk_Main_0.geometry}
        material={materials.Main}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Keyboards+Mouses_Keyboard_Body_0"].geometry}
        material={materials.Keyboard_Body}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/mri/MRIControlPanel-transformed.glb");
