/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [38.46KB] > /Users/cex/Desktop/projects/RxVR-R3F/public/models/MRI/scene-transformed.glb [466.91KB] (-1114%)
Author: Mihail Shegolev (https://sketchfab.com/kekaros509)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-mri-0316c6e93325481db2de156ad0098cae
Title: Sci-Fi MRI
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MRIMachine(props) {
  const { nodes, materials } = useGLTF(
    "/models/mri/mri-machine-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube046_Cube054_None_0.geometry}
        material={materials.None}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/mri/mri-machine-transformed.glb");
