/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Curtains.glb --transform 
Files: Curtains.glb [111.56KB] > C:\Users\tpf1\Desktop\projects\RxVR-2\public\models\seahorse\Curtains-transformed.glb [11.05KB] (90%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Curtains(props) {
  const { nodes, materials } = useGLTF(
    "/models/seahorse/Curtains-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.lambert4SG}
      />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.lambert5SG}
      />
    </group>
  );
}

useGLTF.preload("/models/seahorse/Curtains-transformed.glb");
