/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 seahorse.glb --transform 
Files: seahorse.glb [8.9MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/seahorse/seahorse-transformed.glb [77.91KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Seahorse(props) {
  const { nodes, materials } = useGLTF(
    "/models/seahorse/seahorse-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Walls.geometry}
        material={materials.PaletteMaterial001}
      />
      <instancedMesh
        args={[nodes.CTRL_Baseboard.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.CTRL_Baseboard.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.CTRL_Hole.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.CTRL_Hole.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.DoorFrane.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Door.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back.geometry, materials.PaletteMaterial001, 20]}
        instanceMatrix={nodes.Handle_Back.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door001.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Door001.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.CTRL_Baseboard006.geometry,
          materials.PaletteMaterial001,
          36,
        ]}
        instanceMatrix={nodes.CTRL_Baseboard006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.CTRL_Hole006.geometry, materials.PaletteMaterial001, 35]}
        instanceMatrix={nodes.CTRL_Hole006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane006.geometry, materials.PaletteMaterial001, 36]}
        instanceMatrix={nodes.DoorFrane006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back012.geometry, materials.PaletteMaterial001, 72]}
        instanceMatrix={nodes.Handle_Back012.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door013.geometry, materials.PaletteMaterial001, 29]}
        instanceMatrix={nodes.Door013.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.CTRL_Hole044.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.CTRL_Hole044.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowFrane.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowFrane.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle.geometry, materials.PaletteMaterial001, 76]}
        instanceMatrix={nodes.Handle.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Windows_Sill.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.Windows_Sill.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowL.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL_1.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowL_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowR.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR_1.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowR_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/seahorse/seahorse-transformed.glb");
