/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 seahorse-outer.glb --transform 
Files: seahorse-outer.glb [3.78MB] > /Users/cex/Desktop/projects/RxVR-2/public/models/buildings/seahorse-outer-transformed.glb [52.9KB] (99%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SeahorseOuter(props) {
  const { nodes, materials } = useGLTF(
    "/models/buildings/seahorse-outer-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Walls.geometry}
        material={materials.PaletteMaterial001}
      />
      <instancedMesh
        args={[nodes.WindowFrane.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowFrane.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle.geometry, materials.PaletteMaterial001, 76]}
        instanceMatrix={nodes.Handle.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Windows_Sill.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.Windows_Sill.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.DoorFrane.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Door.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back.geometry, materials.PaletteMaterial001, 20]}
        instanceMatrix={nodes.Handle_Back.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door001.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Door001.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.DoorFrane006.geometry, materials.PaletteMaterial001, 36]}
        instanceMatrix={nodes.DoorFrane006.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Door012.geometry, materials.PaletteMaterial001, 30]}
        instanceMatrix={nodes.Door012.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Handle_Back012.geometry, materials.PaletteMaterial001, 72]}
        instanceMatrix={nodes.Handle_Back012.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowL.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowL_1.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowL_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowR.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.WindowR_1.geometry, materials.PaletteMaterial001, 38]}
        instanceMatrix={nodes.WindowR_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/buildings/seahorse-outer-transformed.glb");
